### ISSUE TITLE
Link's Awakening-Unable to start the game 

### ISSUE THREAD

**Issue by FouzR** [Eeems-Org/remarkable-gameboy#8]
Game reaches point where you can enter your characters name. However, you can't select the save afterwards, cause it isn't created

**Comment by Eeems** [comment]
Do you know if it's due to #7

**Comment by FouzR** [comment]
https://ladecadence.net/trastero/listado%20juegos%20gameboy.html
It appears to be an MBC1 game(the non-dx version at least)
Could also be due to some of the test ROM fails?

**Comment by Eeems** [comment]
Potentially. @calc84maniac any insight?

**Comment by FouzR** [comment]
I can also confirm, Link's Awakening Dx does work(since that's MBC5)

**Comment by calc84maniac** [comment]
Seems to be an issue at https://github.com/Eeems-Org/remarkable-gameboy/blob/b136f7a7323334ed3336e84b5cd4d7aa1c5883db/src/vendor/libqboy/z80mbc.cpp#L44 and https://github.com/Eeems-Org/remarkable-gameboy/blob/b136f7a7323334ed3336e84b5cd4d7aa1c5883db/src/vendor/libqboy/z80mbc.cpp#L78

These shouldn't be checking `ram_mode`, which is checked for its _actual_ usage below these.

Edit: Actually, only the second one does the proper check below it, which I suppose should be copied underneath the first one as well.

**Comment by Eeems** [comment]
This does appear to fix it!

**Comment by Eeems** [comment]
Although, the save is missing after a reset, but at least you can start the game.
